name: dart_vector_examples
description: Examples of algebraic vector with SIMD support
version: 0.0.1
author: Ilya Gyrdymov <ilgyrd@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  dart_vector:
    git:
      url: https://github.com/gyrdym/dart_vector.git

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
