name: linalg
description: linear algebra with dart
version: 0.5.0
author: Ilya Gyrdymov <ilgyrd@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^0.12.0
  mockito: ^2.0.2
  dartdoc: any
