name: linalg
description: linear algebra with dart
version: 2.1.3
author: Ilia Gyrdymov <ilgyrd@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^1.2.0
  mockito: ^3.0.0
  dartdoc: any
  build_runner: ^0.10.0
  build_test: ^0.10.2
