name: ml_linalg
description: SIMD-based linear algebra with dart for machine learning purposes
version: 2.2.1
author: Ilia Gyrdymov <ilgyrd@gmail.com>
homepage: https://github.com/gyrdym/ml_linalg

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^1.2.0
  mockito: ^3.0.0
  dartdoc: any
  build_runner: ^0.10.0
  build_test: ^0.10.2
